# Generated by Django 5.0.3 on 2024-03-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_card',
            field=models.CharField(default='1234566789012', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
