# Generated by Django 5.0.3 on 2024-03-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_id_card_alter_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
    ]
