# Generated by Django 5.0.3 on 2024-04-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpType',
            fields=[
                ('type_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('type_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('screen_mapping_name', models.CharField(blank=True, max_length=255)),
                ('system_flag', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookUpValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_code', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('value_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('attribute1', models.CharField(blank=True, max_length=2000, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=2000, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=2000, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=2000, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=2000, null=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('inactive_fg', models.BooleanField(blank=True, default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.lookuptype')),
            ],
        ),
    ]
