# Generated by Django 5.0.3 on 2024-04-01 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_lookuptype_lookupvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 1, 7, 47, 1, 370928, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='inactive_fg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_card',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
