# Generated by Django 5.0.3 on 2024-04-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_status_member_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.lookupvalue'),
        ),
    ]
